#!/bin/sh
### BEGIN INIT INFO
# Provides:          rpi_stats
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

cd /home/pi/projects        # Modify this line to your OpenRemote Controller installation path

case "$1" in

stop)
        echo "Starting rpi_stats..."
        CAM_PID=`ps auxwww | grep rpi_stat[s] | head -1 | awk '{print $2}'`
        kill -9 $CAM_PID
        ;;

start)
        # start OpenRemote in background mode
        /home/pi/projects/rpi_stats.py > /dev/null 2>&1 &
        echo "rpi_stats started..."
        ;;

restart)
        echo "Stopping rpi_stats..."
        CAM_PID=`ps auxwww | grep rpi_stat[s] | head -1 | awk '{print $2}'`
        kill -9 $CAM_PID
        #sleep 5
        
        echo "Starting rpi_stats..."
               /home/pi/projects/rpi_stats.py > /dev/null 2>&1 &
        ;;
*)
        echo "usage: $0 { start | stop | restart}" >&2
        exit 1
        ;;

esac

